### ISSUE TITLE
Server crash, possible Logistics Pipes issue

### ISSUE THREAD

**Issue by Xariyl** [Xariyl/FishyExperiment812390#19]
@odenthefish 
[Crash log 16_Dec](https://gist.github.com/Xariyl/75d6f09d0787cfc4de8b)

The Nodecraft server is assigned 4GB RAM, and it's showing 100% usage, with CPU usage at 98%. (this is with nobody logged on). This happened a while back when I first started the server, when I initially had 2GB assigned, after I doubled it the usage hovered around 80%. Until today, apparently.

**Comment by Xariyl** [comment]
Manually loaded 'logisticspipes-0.9.3.70' to my client and to the server. RAM usage still very high (was 50% when first loaded, now at 76% as I type this ~10 minutes later). I don't know if this is specifically the issue, but I'm no longer seeing any error messages in the console log.

**Comment by odenthefish** [comment]
Hmm, that probably has something to do with my system, I just started my quarry back up and that is complaining about a routed pipe crashing, 
Block location: World: (748,202,1536), Chunk: (at 12,12,0 in 46,96; contains blocks 736,0,1536 to 751,255,1551), Region: (1,3; contains chunks 32,96 to 63,127, blocks 512,0,1536 to 1023,255,2047)
I can't remember my base location but I think that may be it.

It might be the fact the quarry is running, I'm not sure if it's still going but I'd guess it is, I think I've cut down on my chunk loading a lot but it might be that I have too much stuff going on, I'll see about cutting my chunk loading even more.

The latest update is in the process of being uploaded to the internets, and it will bring updates to Project red and logistics pipes (Two mods I've been neglecting to update) and maybe just having them both updated will help (optimizations, bug fixes ect.)
