### ISSUE TITLE
Warning! Bugs! Don't go adventuring!

### ISSUE THREAD

**Issue by odenthefish** [Xariyl/FishyExperiment812390#20]
@Xariyl 
I created a world to see what type of biome I want to move to or create a second base in, I made it a Biomes O' plenty world and proceeded to explore in creative, currently there appears to be a bug with biomes O' plenty http://mod-buildcraft.com/forums/showthread.php?tid=1966 ~~currently there doesn't appear to  be a new Biomes O' plenty version, I will try and reproduce it again to post a bug report (I want to make sure it isn't something with the minecraft multiMC instance because that one instance has been through quite a few crashes...)~~

I forgot to check Biomes O' plenty and just checked on the curse launcher, they have updated versions! By a long way! :P That will be updated in the next biome :)

**Comment by odenthefish** [comment]
Plus I just found a Biome Id conflict just now... The Mining biome was conflicting with the BOP meadow.
It looks like it can be easily resolved by setting the mining biome ID to 174, though it makes the already generated chunks turn into the meadow biome there doesn't appear to be any other issues.
The next update to the modpack seems like it'll be pretty soon.

**Comment by Xariyl** [comment]
Okay. I don't think we've done any actual building in our mining world? We can change the biome ID and delete the dimension folder from the server. Theoretically it should recreate the mining dimension with the new ID when we try to go through the portal again.

When I get a chance I'll test with a backup of the world.

**Comment by odenthefish** [comment]
I think I still have a quarry, tesseract and enderchest there but other than that I don't think I have anymore things there.

**Comment by odenthefish** [comment]
Probably fixed.
