### ISSUE TITLE
Another server crash, NPE "Ticking world"

### ISSUE THREAD

**Issue by Xariyl** [Xariyl/FishyExperiment812390#21]
Crash log https://gist.github.com/Xariyl/81a5b29f3633cdab3efa

**Comment by odenthefish** [comment]
Hmm, looks like a crash involving codechicken lib.
I'll start working on an update to the modpack today, updating some stuff might fix it.
Is it a recurring crash or did it only happen once so far?

It might be a crash to do with forge its self, could you try updating it to the latest recommended version if you haven't already?

**Comment by Xariyl** [comment]
Currently running forge-1.7.10-10.13.4.1558-1.7.10-universal, which is the latest Recommended version.

Looks like it has crashed twice on January 6. It hadn't crashed since then but I was seeing [a lot of spam in the console](https://gist.github.com/Xariyl/2090ad3e22bc0024ee34) when I looked at it yesterday. I agree it's one of the CCC mods; when I got a chance I was planning to hunt down any chunk loaders floating around and see if disabling them would help.

**Comment by odenthefish** [comment]
I'll look around as well when I get the time, I have a few scattered around.

**Comment by Xariyl** [comment]
Had to kill the overworld gold-farm I made. 

I had the area chunk-loaded for the iron golems, but it kept the giant nether portals active. So pigmen kept spawning, but with no players around to aggro them they would port into the Nether. The nether side was also chunkloaded for the lava tanks. So, the nether side (near Sandriell's base) was so overloaded with pigmen that the game slowed to 1 FPS; couldn't move at all. 

Wished I could have gotten a screenshot but the game was so jerky, lol. Anyway, I destroyed the portal for the gold farm in the overworld so it shouldn't be a problem anymore. No idea what the "chicken" error was; when I went to the coordinates from the console it put me in the middle of the desert near the Iron/Gold farm. So who knows.

**Comment by odenthefish** [comment]
Lol, how much gold did you come out with?
I'm not sure why it'd complain about the chunks of chickens so it does seem to need further investigation.

I have a bedrock-cased room with creative lava tanks because the lava pumps are pretty much creative lava tanks with lag caused by the chunk loading and that kind of stuff, I meant to leave signs informing people to use those endertanks instead, to help the server. 

Also has Sandriell logged on in a while? I haven't noticed but I haven't been on lately.

**Comment by Xariyl** [comment]
Yeah, I don't know unless there is an actual chicken bugged somewhere :)

I haven't seen Sandriell in quite a while, there's been no changes to his base in some time. Even I haven't been on too much lately, I've actually been goofing around and testing some 1.8.9 mods. I should probably make more of an effort to be on, since I am paying for it, lol.

**Comment by Xariyl** [comment]
As for the gold... um... well, I had put myself in creative mode. And for "fairness" I decided to clear out all the gold and misc crap I had collected while flying around. Except... um... on accident I double-clicked the big pink X in the creative inventory. And... um... it deleted _ALL_ of my gear. Everything. All my tools, weapons, and armor that I had been carrying around just disappeared.

I've got the resources to redo it all, but still... frustrating.

So to answer your question... no gold :(

poop.

**Comment by odenthefish** [comment]
You can have some of my resources! I don't really have an easy way of producing enderium for enderium tools but it's pretty quick and somewhat easy in the smeltery, and I have all the boxes for crafting Flan's mod guns if you need to make more guns/ammo.
